### 1. Numpy Installation
- ##### pip install numpy==1.26.4

In [3]:
# Checking Numpy version
import numpy as np
print(np.__version__)

1.26.4


#### Array from List

In [6]:
fruits = ['apple', 'mango', 'banana']
print('List:',fruits)
arr = np.array(fruits)
print('\nArray:', arr)

List: ['apple', 'mango', 'banana']

Array: ['apple' 'mango' 'banana']


In [7]:
print('Type of Array:', type(arr))

Type of Array: <class 'numpy.ndarray'>


#### Array from Tuple

In [8]:
fruits = ('apple', 'mango', 'banana')
print('Tuple:', fruits)
arr = np.array(fruits)
print('\nArray:', arr)

Tuple: ('apple', 'mango', 'banana')

Array: ['apple' 'mango' 'banana']


#### Array from random module

In [9]:
arr = np.random.rand(2, 2)
print('\nRandom array:\n', arr)


Random array:
 [[0.043867   0.78928954]
 [0.71985349 0.75439875]]


In [10]:
arr = np.random.randint(5, 15, size=(2, 3))  # From 5 to 14
print('\nRandom integers:\n', arr)


Random integers:
 [[ 8  5  8]
 [10 13  9]]


### 2. Difference between Array and List

In [11]:
fruits = [2, 'apple', 3.0]
print(fruits)

[2, 'apple', 3.0]


In [12]:
arr2 = np.array([2, 'apple', 3.0])
print(arr2)
print(arr2.dtype)

['2' 'apple' '3.0']
<U32


##### Array cannot store mixed type data

### 3. Default data types of array

In [13]:
arr3 = np.array([2, 4, 6])
print(arr3)
print(arr3.dtype)

[2 4 6]
int32


In [14]:
arr3 = np.array([2.0, 4.0, 6.0])
print(arr3)
print(arr3.dtype)

[2. 4. 6.]
float64


### 4. Dimension of Arrays

* ##### 0-D Arrays

In [15]:
arr1 = np.array(34)
print(arr1)
print('Dimension:', arr1.ndim)

34
Dimension: 0


- #### 1-D Arrays

In [16]:
arr2 = np.array([10, 20, 30, 40])
print(arr2)
print('Dimension:', arr2.ndim)

[10 20 30 40]
Dimension: 1


- #### 2-D Arrays

In [17]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Dimension:', arr3.ndim)

[[1 2 3]
 [4 5 6]]
Dimension: 2


- #### 3-D Arrays

In [18]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4)
print('Dimension:', arr4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension: 3


### 4. Specifying data types of Array
- ##### Integer Arrays

In [19]:
arr3 = np.array([2.9, 4.0, 6.0], dtype = 'int8')
print(arr3)
print(arr3.dtype)

[2 4 6]
int8


In [20]:
arr3 = np.array([152, 10, 90], dtype = 'int8')
print(arr3)
print(arr3.dtype)

[-104   10   90]
int8


C:\Users\kamra\AppData\Local\Temp\ipykernel_21908\522668544.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 152 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr3 = np.array([152, 10, 90], dtype = 'int8')


In [21]:
arr3 = np.array([152, 10, 90], dtype = 'int16')
print(arr3)
print(arr3.dtype)

[152  10  90]
int16


- ##### Floating Arrays

In [22]:
arr = np.array([1.1234, 2.3456, 3.5678], dtype=np.float16)
print(arr)
print(arr.dtype)

[1.123 2.346 3.568]
float16


- 📏 Range: ~±65,504
- 🔬 Precision: ~3 decimal digits
- 🧠 Good for saving memory but less accurate.

In [23]:
arr = np.array([1.123456, 2.345678, 3.567891], dtype=np.float32)
print(arr)
print(arr.dtype)

[1.123456 2.345678 3.567891]
float32


- 📏 Range: ~±3.4 × 10^38
- 🔬 Precision: ~6-7 decimal digits
- ✅ Commonly used in ML and DL.

In [24]:
np.set_printoptions(precision=17)  # show up to 17 digits
arr = np.array([1.1234567890123, 2.3456789012345, 3.5678912345678], dtype=np.float64)
print(arr)
print(arr.dtype)

[1.1234567890123 2.3456789012345 3.5678912345678]
float64


- 📏 Range: ~±1.8 × 10^308
- 🔬 Precision: ~15-17 decimal digits
- ✅ Best for numerical accuracy.

### 5. Array Attributes

In [11]:
# Shape of array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Shape:', arr3.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [12]:
# size of array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Size:', arr3.size)

[[1 2 3]
 [4 5 6]]
Size: 6


In [13]:
# itemsize
arr3 = np.array([152, 10, 90], dtype = 'int16')
print(arr3)
print('Itemsize:', arr3.itemsize)

[152  10  90]
Itemsize: 2


### 6. Array Methods

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print('Original array:', arr)
print('Reshaped array:\n', reshaped)


Original array: [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [30]:
arr = np.array([10, 50, 30, 5])
print('Maximum number of array:', arr.max())

Maximum number of array: 50


In [31]:
arr = np.array([10, 50, 30, 5])
print('Minimum number of array:', arr.min())

Minimum number of array: 5


In [ ]:
arr = np.array([10, 50, 30, 5])
print(arr.argmax())  # Gives the Index of maximum value
print(arr.argmin())  # Gives the Index of minimum value

1
3


In [35]:
arr = np.array([1, 2, 3])
expanded = np.expand_dims(arr, axis=0)  # Add row dimension
print(expanded)
print(expanded.shape)


[[1 2 3]]
(1, 3)


In [36]:
expanded = np.expand_dims(arr, axis=1)  # Add column dimension
print(expanded)
print(expanded.shape)


[[1]
 [2]
 [3]]
(3, 1)


### 7. Accessing elements

In [54]:
arr3 = np.array(['apple', 'banana', 'cherry', 'mango', 'orange'])
print(arr3[2])
print(arr3[-2])
print(arr3[1:4])

cherry
mango
['banana' 'cherry' 'mango']


In [66]:
# accessing elements of 2D array
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
print(arr3)
print('--------------------')
print(arr3[0:2, 1:])

[[10 20 30]
 [40 50 60]]
--------------------
[[20 30]
 [50 60]]


#### 8. Type Casting in Array

In [37]:
arr = np.array([1, 2, 3, 4])
float_arr = arr.astype(float)
print(float_arr)
print(float_arr.dtype)

[1. 2. 3. 4.]
float64


In [38]:
arr = np.array([1.7, 2.2, 3.9])
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[1 2 3]
int32


In [39]:
arr = np.array([10, 20, 30])
str_arr = arr.astype(str)
print(str_arr)
print(str_arr.dtype)

['10' '20' '30']
<U11


### 9. Creation Routines

* #### Empty

In [2]:
arr = np.empty([3,3], dtype = 'int')
print(arr)

[[-537329408        545    5570638]
 [   6225997    4718676    4522066]
 [   4456513         83          0]]


In [4]:
arr2 = np.empty([3,3], dtype = 'float')
print(arr2)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.11454530e-321]
 [5.08566454e-028 4.11366171e+223 1.02303531e+200]]


* #### Zeros

In [7]:
arr = np.zeros([3, 3] )
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* #### Ones

In [10]:
# numpy.ones(shape,dtype)
x = np.ones([2,2])
print(x)

[[1. 1.]
 [1. 1.]]


* #### Eye

In [15]:
# eye
arr  = np.eye(4, k = 2)
print(arr)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
arr = np.identity(4, dtype='int')
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [24]:
# arange
arr = np.arange(10, 105, 5)
print(arr)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [27]:
li = range(10, 105, 5)
arr  = np.array(li)
print(arr)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [35]:
x = np.array([1,2])
print(x)
x = np.asmatrix(x)
print(x)


[1 2]
[[1 2]]


### 10. Arthimetic Operation

In [ ]:
# Addition
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 + arr2)
print('-----------------')
print(np.add(arr1, arr2))

[ 3  9 12 10]
-----------------
[ 3  9 12 10]


In [ ]:
# Subtraction
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 - arr2)
print('-----------------')
print(np.subtract(arr1, arr2))

[ 1 -1  0  6]
-----------------
[ 1 -1  0  6]


In [ ]:
# Multiplication
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 * arr2)
print('-----------------')
print(np.multiply(arr1, arr2))

[ 2 20 36 16]
-----------------
[ 2 20 36 16]


In [ ]:
# Matrix multiplication
arr1 = np.array([2,4,6,8])
print(arr1.shape)
print(arr1)
print('-----------------')
arr2 = np.array([[1,5,6,2], [1,3,5,7], [1,4,6,8], [1,3,4,4]])
print(arr2)
print(arr2.shape)
print(np.matmul(arr1, arr2))

(4,)
[2 4 6 8]
-----------------
[[1 5 6 2]
 [1 3 5 7]
 [1 4 6 8]
 [1 3 4 4]]
(4, 4)
[ 20  70 100 112]


In [54]:
# Division
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 / arr2)
print('-----------------')
print(np.divide(arr1, arr2))

[2.  0.8 1.  4. ]
-----------------
[2.  0.8 1.  4. ]


In [25]:
# Modulus
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 % arr2)
print('-----------------')
print(np.mod(arr1, arr2))
print(np.remainder(arr1, arr2))

[0 4 0 0]
-----------------
[0 4 0 0]
[0 4 0 0]


In [41]:
# Exponentiation
arr = np.array([2, 3, 4])
print(arr ** 2)          
print(np.power(arr, 3))


[ 4  9 16]
[ 8 27 64]


In [50]:
# Broadcasting
arr = np.array([1, 2, 3])
result = arr + 5
print(result)


[6 7 8]


### 11. Universal Functions

In [ ]:
# Square root
arr = np.array([4, 9, 16])
print(np.sqrt(arr))


[2. 3. 4.]


In [ ]:
# Exponential (e^x)
arr = np.array([1, 2, 3])
print(np.exp(arr))


[ 2.718281828459045  7.38905609893065  20.085536923187668]


In [45]:
# absolute value
arr = np.array([-1, -2, 3])
print(np.abs(arr))

[1 2 3]


In [ ]:
arr = np.array([1, np.e, np.e**2])
print(np.log(arr))


In [49]:
# Natural logarithm (base e)
arr = np.array([23, 100, 230])
print(np.log(arr))


[3.1354942159291497 4.605170185988092  5.438079308923196 ]


### 12. Comparison operators

In [58]:
# greater
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 > arr2)
print('-----------------')
print(np.greater(arr1, arr2))

[ True False False  True]
-----------------
[ True False False  True]


In [40]:
# Lesser
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 < arr2)
print('-----------------')
print(np.less(arr1, arr2))

[False  True False False]
-----------------
[False  True False False]


### 13. Sorting

In [60]:
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1],
[29, 32, 11, 9]])
print(arr2D)
print('----------------')
arr2D.sort(axis=0)
print('Sorted Array : ')
print(arr2D)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
----------------
Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]


In [67]:
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1],
[29, 32, 11, 9]])
print(arr2D)
print('----------------')
arr2D.sort(axis=0)
print('Sorted Array : ')
print(arr2D)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
----------------
Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]
