In [1]:
import numpy as np
print(np.__version__)

2.2.4


In [2]:
fruits = ['apple', 'mango', 'banana']
print('List:',fruits)
arr = np.array(fruits)
print('\nArray:', arr)

List: ['apple', 'mango', 'banana']

Array: ['apple' 'mango' 'banana']


In [3]:
arr = np.random.rand(2, 2)
print('\nRandom array:\n', arr)


Random array:
 [[0.71773402 0.69793345]
 [0.6652336  0.36273843]]


In [13]:
arr = np.random.randint(0, 100, (2, 2))
print(arr)

[[69  2]
 [94 78]]


In [18]:
arr3 = np.array([23, 41, 10], dtype = 'int8')
print(arr3)
print(arr3.dtype)

[23 41 10]
int8


In [19]:
arr3 = np.array([230, -410, 10], dtype = 'int16')
print(arr3)
print(arr3.dtype)

[ 230 -410   10]
int16


In [20]:
arr3 = np.array([33000, -410, 10], dtype = 'int16')
print(arr3)
print(arr3.dtype)

OverflowError: Python integer 33000 out of bounds for int16

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr.shape)
reshaped = arr.reshape(7, 1)
print('Original array:', arr)
print('Reshaped array:\n', reshaped)

(7,)
Original array: [1 2 3 4 5 6 7]
Reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [28]:
arr = np.array([1, 2, 3])
print(arr.shape)
expanded = np.expand_dims(arr, axis=1)  # Add row dimension
print(expanded)
print(expanded.shape)

(3,)
[[1]
 [2]
 [3]]
(3, 1)


In [29]:
arr3 = np.array(['apple', 'banana', 'cherry', 'mango', 'orange'])
print(arr3[2])
print(arr3[-2])
print(arr3[1:4])

cherry
mango
['banana' 'cherry' 'mango']


In [30]:
# accessing elements of 2D array
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
print(arr3)
print('--------------------')

[[10 20 30]
 [40 50 60]]
--------------------


In [35]:
print(arr3[1][2])

60


In [36]:
print(arr3[0][0:2])

[10 20]


In [37]:
print(arr3[0, 0:2])

[10 20]


In [60]:
arr3[:, 1:]

array([[20, 30],
       [50, 60]])

In [63]:
print('Abdullah:', arr3[0:2, 1])
print('Imran', arr3[0, 1:2][1, 1:2])

Abdullah: [20 50]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [3]:
import numpy as np
arr = np.zeros([3, 3], dtype = 'int')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
arr  = np.eye(4, k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [6]:
arr  = np.eye(4, k=2)
print(arr)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr = np.array([10, 20, 30])
print(arr)
print(arr.dtype)

[10 20 30]
int64


In [8]:
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1],
[29, 32, 11, 9]])
print(arr2D)
print('----------------')
arr2D.sort(axis=1)
print('Sorted Array : ')
print(arr2D)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
----------------
Sorted Array : 
[[ 1  2  7  8]
 [ 1  2  3  3]
 [ 9 11 29 32]]
